### ISSUE TITLE
[CLOSED] TODO From Dec24

### ISSUE THREAD

**Issue by llmhyy** [llmhyy/evosuite-plus-plus#132]
<a href="https://github.com/Cary-Xx"><img src="https://avatars0.githubusercontent.com/u/28557849?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Cary-Xx](https://github.com/Cary-Xx)**
_Tuesday Dec 24, 2019 at 14:12 GMT_
_Originally opened as https://github.com/llmhyy/evosuite_progress/issues/132_

----

**TODOs**

- [x] Mutation issue: mutationChange() is fixed by truncating the statements after target method call, mutationInsert() needs to be amended by disallowing inserting after target.

- [x] Re-calculate time: If the method achieves the same coverage (e.g., 40%) (not 100%) for both strategies, we record the timestamp when the coverage first reaches 40%.

- [ ] Construct rough idea on how to construct objects: 

1. Global variable
2. Child class of interface or abstract class
3. Consecutive object assignments
4. Calling correct constructor ( if exists )
**Preliminary Goal :** Retrieving all relevant variables (including all) and their corresponding set places

- [x] Run trivial flag method such as _StringUtils.isNotEmpty(string)_ using new time recording rule and compare the performances
